version: "3.9"

services:
  vc-backend:
    container_name: vc-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: vc-backend:latest

    env_file:
      - .env

    ports:
      - "3000:3000"
      - "40000-40999:40000-40999/udp"
      - "40000-40999:40000-40999/tcp"

    restart: unless-stopped